# Generated by Django 4.0.5 on 2022-06-20 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=264, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('atm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.atm')),
                ('bank_branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.bankbranch')),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.bank')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('operation', models.CharField(max_length=264, unique=True)),
                ('bank_branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.bankbranch')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.bankbranch')),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.bank')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.customer')),
            ],
        ),
    ]
