# Generated by Django 4.0.5 on 2022-06-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_rename_customerregister_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='operation',
            field=models.CharField(max_length=264),
        ),
    ]
