# Generated by Django 4.0.5 on 2022-06-21 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_alter_transaction_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank_app.customer'),
            preserve_default=False,
        ),
    ]
