# Generated by Django 4.0.5 on 2022-06-22 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0006_alter_transaction_atm_id_alter_transaction_branch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='atm_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='branch_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='atm',
            name='bank_branch_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank_app.bankbranch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_id',
            field=models.ForeignKey(default=1323, on_delete=django.db.models.deletion.CASCADE, to='bank_app.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_branch_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bank_app.bankbranch'),
            preserve_default=False,
        ),
    ]
