# Generated by Django 4.0.5 on 2022-06-23 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0007_remove_transaction_atm_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbranch',
            name='bank_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank', to='bank_app.bank'),
        ),
    ]
