# Generated by Django 4.0.5 on 2022-06-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0008_alter_bankbranch_bank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbranch',
            name='bank_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.bank'),
        ),
    ]
