# Generated by Django 4.0.5 on 2022-06-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0009_alter_bankbranch_bank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='operation',
            field=models.CharField(choices=[('card_to_card', 'Card to Card'), ('withdraw', 'Withdraw'), ('deposit', 'Deposit')], max_length=264),
        ),
    ]
