# Generated by Django 4.0.5 on 2022-06-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0010_alter_transaction_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='bank_id',
        ),
    ]
